select distinct
    trim(genre_name) as genre_name
from {{ ref('int_books_cleaned') }},
    unnest(split(genres, ',')) as genre_name
where trim(genre_name) in (
    'fiction',
    'fantasy',
    'romance',
    'mystery',
    'nonfiction',
    'science-fiction',
    'historical-fiction',
    'young-adult',
    'thriller',
    'biography',
    'memoir',
    'horror',
    'humor-and-comedy',
    'poetry',
    'philosophy',
    'psychology',
    'religion',
    'science',
    'self-help',
    'spirituality',
    'sports',
    'suspense',
    'travel',
    'crime',
    'paranormal',
    'manga',
    'graphic-novels',
    'cookbooks',
    'music',
    'chick-lit',
    'christian',
    'business',
    'history'
)