version: 2

models:
  - name: dim_books
    columns:
      - name: book_id
        tests:
          - unique
          - not_null

  - name: fact_ratings
    columns:
      - name: book_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_books')
              field: book_id
      - name: rating
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5]
              quote: false